# Imports

In [1]:
# Import libraries
import pandas as pd
import datetime as dt
import yfinance as yf
import numpy as np
from datetime import datetime

# Company tickers

In [8]:
# Get symbols for the top 1000 companies in the US by market cap
symbols = pd.read_csv("data/largest companies list.csv")["Symbol"]

# Stock price data

In [9]:
# For importing other data
start_date = dt.datetime(1980,1,1).date()
today_date = dt.datetime.now().date()

stocks = [stock.replace(".", "-") for stock in symbols]
stocks_df = yf.download(stocks, start=start_date, end=today_date, interval="1d")

# low_df = stocks_df.loc[:,"Low"]
# low_df.columns = [stock.replace("-", ".") for stock in low_df.columns]
# low_df.to_csv("data/low.csv") 

# high_df = stocks_df.loc[:,"High"]
# high_df.columns = [stock.replace("-", ".") for stock in high_df.columns]
# high_df.to_csv("data/high.csv") 

# volume_df = stocks_df.loc[:,"Volume"]
# volume_df.columns = [stock.replace("-", ".") for stock in volume_df.columns]
# volume_df.to_csv("data/volume.csv") 

stocks_df = stocks_df.loc[:,"Adj Close"]
stocks_df.columns = [stock.replace("-", ".") for stock in stocks_df.columns]
stocks_df.to_csv("data/price.csv")

stocks_df

[*********************100%***********************]  1005 of 1005 completed

20 Failed downloads:
- ABC: No data found, symbol may be delisted
- UNVR: No data found, symbol may be delisted
- UMPQ: No data found, symbol may be delisted
- HZNP: No data found, symbol may be delisted
- LSI: No data found, symbol may be delisted
- SGFY: No data found, symbol may be delisted
- HHC: No data found, symbol may be delisted
- PDCE: No data found, symbol may be delisted
- SYNH: No data found, symbol may be delisted
- FISV: No data found, symbol may be delisted
- BKI: No data found, symbol may be delisted
- RE: No data found, symbol may be delisted
- SIVB: No data found, symbol may be delisted
- IAA: No data found, symbol may be delisted
- FRC: No data found, symbol may be delisted
- PKI: No data found, symbol may be delisted
- WWE: No data found, symbol may be delisted
- OSH: No data found, symbol may be delisted
- COUP: No data found, symbol may be delisted
- STOR: No data found, symbol may be delisted

,A,AA,AAL,AAP,AAPL,ABBV,ABC,ABNB,ABT,ACGL,...,YUM,Z,ZBH,ZBRA,ZG,ZI,ZION,ZM,ZS,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
1980-01-02,NaN,3.217068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-01-03,NaN,3.187954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-01-04,NaN,3.187954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-01-07,NaN,3.246180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-01-08,NaN,3.289852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-04,128.880005,26.809999,13.35,55.630001,189.429993,144.149994,NaN,133.699997,105.190002,81.989998,...,125.650002,44.090000,116.889999,239.369995,42.330002,14.71,38.680000,68.160004,198.259995,182.119995
2023-12-05,127.879997,25.240000,13.13,53.160000,193.419998,144.570007,NaN,133.710007,104.349998,81.849998,...,124.379997,44.290001,115.820000,234.360001,42.520000,14.48,37.389999,68.720001,198.910004,179.649994
2023-12-06,128.910004,25.120001,13.48,55.160000,192.320007,146.380005,NaN,135.309998,104.940002,79.970001,...,124.809998,45.090000,116.129997,234.130005,43.490002,15.50,37.150002,70.940002,197.910004,182.000000
2023-12-07,128.679993,24.940001,13.91,56.250000,194.270004,147.970001,NaN,139.839996,104.050003,78.339996,...,124.269997,46.730000,117.290001,233.229996,45.009998,15.24,38.380001,71.930000,200.050003,181.830002
2023-12-08,127.199997,25.020000,13.76,56.270000,195.710007,149.279999,NaN,140.679993,104.510002,79.300003,...,124.339996,46.410000,117.300003,236.130005,44.660000,15.64,38.930000,73.059998,198.800003,184.600006

# Features

## Categorical variable(s)

In [ ]:
# ############## This no longer works due to changes in yahoo api. 

# # Get the sector associated with each company.
# symbols_data = yf.Tickers(list(symbols))
# sectors = []
# stocks = []
# range_tqdm = tqdm(range(len(symbols)))
# for i in range_tqdm:
#     try:
#         sectors.append(symbols_data.tickers[symbols[i]].info["sector"])
#     except KeyError:
#         pass
#     except TypeError:
#         pass
#     else:
#         stocks.append(symbols[i])

In [ ]:
# sector_stock = pd.Series(data=sectors, index=stocks)
# cat_variables = pd.DataFrame(columns=symbols, data=[sector_stock])
# cat_variables.index = ["sectors"]
# cat_variables.to_csv("data/categorical.csv")
# cat_variables

## Numerical features

In [11]:
first_date = stocks_df.index[0]
last_date = stocks_df.index[-1]

In [7]:
first_date = datetime.strptime("1990-01-02", "%Y-%m-%d")
last_date = datetime.strptime("2022-12-27", "%Y-%m-%d")

In [8]:
leading_indicators = pd.read_csv(f"https://stats.oecd.org/SDMX-JSON/data/MEI_CLI/LOLITOAA+BSCICP03+CSCICP03.USA.M/all?startTime={first_date.year}-0{first_date.month}&endTime={last_date.year}-{last_date.month}&dimensionAtObservation=allDimensions&contentType=csv")

remap = {"BSCICP03": "BCI", # Business confidence indicator (BCI)
         "CSCICP03":"CCI", # Comsumer confidence indicator (CCI)
         "LOLITOAA":"CLI"} # Composite leading indicator (CLI)
leading_indicators.replace({"SUBJECT": remap},inplace=True)

leading_indicators = leading_indicators.drop(columns=["Subject",
                                                      "LOCATION",
                                                      "Country",
                                                      "FREQUENCY",
                                                      "Frequency",
                                                      "Time",
                                                      "Unit Code",
                                                      "Unit",
                                                      "PowerCode Code",
                                                      "PowerCode",
                                                      "Reference Period Code",
                                                      "Reference Period",
                                                      "Flag Codes",
                                                      "Flags"]
                                             ).set_index("TIME")

leading_indicators = leading_indicators.pivot(columns="SUBJECT", values="Value")
leading_indicators.index = pd.to_datetime(leading_indicators.index)
leading_indicators

SUBJECT          BCI        CCI       CLI
TIME
1990-01-01  98.82303  100.65090  99.79321
1990-02-01  99.03568  100.63290  99.82352
1990-03-01  99.20376  100.70180  99.82258
1990-04-01  99.25664  100.75420  99.74667
1990-05-01  99.18031  100.62450  99.57418
...              ...        ...       ...
2022-08-01  99.77292   96.45410  99.37940
2022-09-01  99.54463   96.66862  99.21077
2022-10-01  99.31287   96.78098  99.06943
2022-11-01  99.09203   96.84678  98.95784
2022-12-01  98.91054   97.06240  98.88888

[396 rows x 3 columns]

In [9]:
more_indicators = pd.read_csv(f"https://stats.oecd.org/SDMX-JSON/data/KEI/PRINTO01+PRMNTO01+PRCNTO01+SLRTTO01+SLRTCR03+LOLITOAA+BSCICP02+LFEMTTTT+LCEAMN01+PIEAMP01+CPALTT01+MANMM101+MABMM301+IR+IRSTCI01+IR3TIB01+IRLTLT01.USA.ST.M/all?startTime={first_date.year}-0{first_date.month}&endTime={last_date.year}-{last_date.month}&dimensionAtObservation=allDimensions&contentType=csv")

more_indicators = more_indicators.drop(columns=["SUBJECT",
                                                "LOCATION",
                                                "Country",
                                                "MEASURE",
                                                "Measure",
                                                "FREQUENCY",
                                                "Frequency",
                                                "Time",
                                                "Unit Code",
                                                "Unit",
                                                "PowerCode Code",
                                                "PowerCode",
                                                "Reference Period Code",
                                                "Reference Period",
                                                "Flag Codes",
                                                "Flags"]
                                       ).set_index("TIME")

more_indicators = more_indicators.pivot(columns="Subject", values="Value")
more_indicators.index = pd.to_datetime(more_indicators.index)

more_indicators.columns = ["3 month interbank rate",
                           "Broad money",
                           "Construction",
                           "Consumer prices",
                           "Manufacturing hourly earnings",
                           "Industrial production",
                           "Leading indicator",
                           "Long-term interest rate", # Long-term interest rates refer to government bonds maturing in ten years
                           "Manufacturing confidence indicator",
                           "Narrow money",
                           "Overnight interbank rate",
                           "Car registrations",
                           "Manufacturing producer prices",
                           "Retail trade volume",
                           "Total employment",
                           "Total manufacturing"]

more_indicators

,3 month interbank rate,Broad money,Construction,Consumer prices,Manufacturing hourly earnings,Industrial production,Leading indicator,Long-term interest rate,Manufacturing confidence indicator,Narrow money,Overnight interbank rate,Car registrations,Manufacturing producer prices,Retail trade volume,Total employment,Total manufacturing
TIME,,,,,,,,,,,,,,,,
1990-01-01,8.16,26.291189,40.385124,53.751419,52.855468,61.105826,99.793216,8.21,-5.6,26.324891,8.23,138.407385,60.738345,67.509220,119081.0,61.244983
1990-02-01,8.22,26.394135,41.024431,54.004565,53.458382,61.667677,99.823520,8.47,-1.8,26.414251,8.24,125.908215,60.468876,66.675442,119059.0,62.080383
1990-03-01,8.35,26.484629,41.498263,54.299903,53.759839,61.961093,99.822577,8.59,-0.2,26.526779,8.28,126.359833,60.522770,66.538278,119203.0,62.382895
1990-04-01,8.42,26.580103,40.863316,54.384285,53.659354,61.815277,99.746669,8.79,0.0,26.679023,8.26,124.925284,60.684452,66.133992,118852.0,62.128573
1990-05-01,8.35,26.571801,39.556166,54.510858,53.960811,62.001339,99.574184,8.76,-1.0,26.616139,8.18,121.259215,60.953921,65.879515,119151.0,62.321634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-01,2.76,179.823331,165.368746,124.957703,126.360744,102.333127,99.379405,2.90,5.8,677.811334,2.33,37.856147,135.539747,121.410486,158694.0,100.151181
2022-09-01,3.21,178.705034,164.441767,125.226461,126.913415,102.624461,99.210768,3.52,2.0,671.228456,2.56,38.161652,135.828618,120.413240,158850.0,100.392831
2022-10-01,3.85,177.942068,163.864095,125.734441,127.516329,102.508581,99.069427,3.98,0.4,665.218147,3.08,40.313475,136.889787,121.484740,158593.0,100.525829
2022-11-01,4.46,177.659795,164.914074,125.607446,128.621671,102.170856,98.957837,3.89,-2.0,660.766679,3.78,40.765093,136.272164,119.371187,158527.0,99.776833
2022-12-01,4.51,177.318578,164.796803,125.221820,128.973371,100.598801,98.888878,3.62,-3.2,655.997485,4.10,37.603772,131.749933,118.300105,159244.0,97.682796

## Combining numerical features into a daily-dataframe

Using "daily" since stock prices are given with daily fequency.

In [13]:
features_monthly = pd.concat([leading_indicators,
                              more_indicators], axis = "columns")

features_monthly.loc[last_date,:] = [np.nan] * len(features_monthly.columns) # This is to ensure that every day in the stocks_df has a corresponding column
features_daily = features_monthly.resample("D").nearest()

# Not sure exactly what this indicator was so I removed it.
features_daily = features_daily.drop(columns = ["Leading indicator"])

features_daily = features_daily.fillna(method="ffill")
features_daily.index.name = "Date"
features_daily.to_csv("data/features.csv")

features_daily

,BCI,CCI,CLI,3 month interbank rate,Broad money,Construction,Consumer prices,Manufacturing hourly earnings,Industrial production,Long-term interest rate,Manufacturing confidence indicator,Narrow money,Overnight interbank rate,Car registrations,Manufacturing producer prices,Retail trade volume,Total employment,Total manufacturing
Date,,,,,,,,,,,,,,,,,,
1990-01-01,98.82303,100.6509,99.79321,8.16,26.291189,40.385124,53.751419,52.855468,61.105826,8.21,-5.6,26.324891,8.23,138.407385,60.738345,67.509220,119081.0,61.244983
1990-01-02,98.82303,100.6509,99.79321,8.16,26.291189,40.385124,53.751419,52.855468,61.105826,8.21,-5.6,26.324891,8.23,138.407385,60.738345,67.509220,119081.0,61.244983
1990-01-03,98.82303,100.6509,99.79321,8.16,26.291189,40.385124,53.751419,52.855468,61.105826,8.21,-5.6,26.324891,8.23,138.407385,60.738345,67.509220,119081.0,61.244983
1990-01-04,98.82303,100.6509,99.79321,8.16,26.291189,40.385124,53.751419,52.855468,61.105826,8.21,-5.6,26.324891,8.23,138.407385,60.738345,67.509220,119081.0,61.244983
1990-01-05,98.82303,100.6509,99.79321,8.16,26.291189,40.385124,53.751419,52.855468,61.105826,8.21,-5.6,26.324891,8.23,138.407385,60.738345,67.509220,119081.0,61.244983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,98.91054,97.0624,98.88888,4.51,177.318578,164.796803,125.221820,128.973371,100.598801,3.62,-3.2,655.997485,4.10,37.603772,131.749933,118.300105,159244.0,97.682796
2022-12-24,98.91054,97.0624,98.88888,4.51,177.318578,164.796803,125.221820,128.973371,100.598801,3.62,-3.2,655.997485,4.10,37.603772,131.749933,118.300105,159244.0,97.682796
2022-12-25,98.91054,97.0624,98.88888,4.51,177.318578,164.796803,125.221820,128.973371,100.598801,3.62,-3.2,655.997485,4.10,37.603772,131.749933,118.300105,159244.0,97.682796
2022-12-26,98.91054,97.0624,98.88888,4.51,177.318578,164.796803,125.221820,128.973371,100.598801,3.62,-3.2,655.997485,4.10,37.603772,131.749933,118.300105,159244.0,97.682796
2022-12-27,98.91054,97.0624,98.88888,4.51,177.318578,164.796803,125.221820,128.973371,100.598801,3.62,-3.2,655.997485,4.10,37.603772,131.749933,118.300105,159244.0,97.682796